### ISSUE TITLE
Dependensy on new version not work

### ISSUE THREAD

**Issue by mgusevstudio** [doorbash/colyseus-kotlin#14]
Hello

Thanks for the quick fix for API 24 and lower! Everything works correctly if the source code of your library is included as a separate module.

But, when using the dependency "implementation 'io.github.doorbash: colyseus-kotlin: 0.14.2'" there is an error.

![image](https://user-images.githubusercontent.com/49568966/114911945-1d286880-9e28-11eb-9853-c96cca01a904.png)

**Comment by doorbash** [comment]
Hi @mgusevstudio Thanks for the report. Adding

```groovy
maven { url 'https://jitpack.io' }
```

to your root `build.gradle` should fix the problem.

**Comment by mgusevstudio** [comment]
Did not work. Apparently I'm doing something wrong (

![image](https://user-images.githubusercontent.com/49568966/114920139-c9228180-9e31-11eb-9ae6-10d51aeaf64c.png)

**Comment by doorbash** [comment]
Fixed in `0.14.4`

**Comment by mgusevstudio** [comment]
Everything is fine in version 0.14.5, thanks!
