### ISSUE TITLE
Error during Handshake Serializer

### ISSUE THREAD

**Issue by Meabo** [doorbash/colyseus-kotlin#15]
Hello @doorbash, thanks for your amazing client sdk for Colyseus.

I'm having an issue during the handshake (Serializer)

W/System.err: java.lang.NullPointerException
        **at io.colyseus.serializer.SchemaSerializer.handshake(SchemaSerializer.kt:42)**
        at io.colyseus.Room.parseMessage(Room.kt:92)
        at io.colyseus.Room.access$parseMessage(Room.kt:20)
        at io.colyseus.Room$connect$3.invoke(Room.kt:75)
        at io.colyseus.Room$connect$3.invoke(Room.kt:20)
        at io.colyseus.Connection.onMessage(Connection.kt:66)
        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:598)
        at org.java_websocket.drafts.Draft_6455.processFrameBinary(Draft_6455.java:862)
        at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:821)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:379)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:216)
        
 **Client-side:** 
 Library: 'io.github.doorbash:colyseus-kotlin:0.14.5'
 Schema: 
 
 ```
class GameLobbySchema : Schema() {
    @SchemaField("0/boolean")
    var boo = Boolean.default
    }
```

**Server-side:**
Library: colyseus@0.14.13
Library Schema: colyseus-schema@1.0.22
Schema: 

```
class GameLobbySchema extends Schema {
    @type("boolean")
    boo: Boolean;
}
```

I tried many things, but I'm completly locked right now, can you help me please 😊 ?
Thanks

**Comment by doorbash** [comment]
Well I could not reproduce it here. `handshake` is not getting called for me because here:

https://github.com/doorbash/colyseus-kotlin/blob/003ee6d121b6fcee38573e91fb331063d38e7255/src/main/java/io/colyseus/Room.kt#L91

`bytes.size` is equal to `offset` with value of 6

And one more thing: I changed `boo`'s value every second and server is not sending schema changes to client so I guess it's a `colyseus/colyseus` bug

for a workaround maybe try adding a nested schema and define `boo` there.

**Comment by doorbash** [comment]
Hi @Meabo I've just created a new repository to reproduce it:
https://github.com/doorbash/colyseus-kotlin-example

 It's working fine for me.

**Comment by Meabo** [comment]
Thanks @doorbash, I'll investigate further on the server side (Client is working well)

**Comment by taluks** [comment]
I have the same problem, if room state name on server side not "MyRoomState".

> java.lang.NullPointerException
> 	at io.colyseus.serializer.SchemaSerializer.handshake(SchemaSerializer.kt:42)
> 	at io.colyseus.Room.parseMessage(Room.kt:92)
> 	at io.colyseus.Room.access$parseMessage(Room.kt:20)
> 	at io.colyseus.Room$connect$3.invoke(Room.kt:75)
> 	at io.colyseus.Room$connect$3.invoke(Room.kt:20)
> 	at io.colyseus.Connection.onMessage(Connection.kt:66)
> 	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:598)
> 	at org.java_websocket.drafts.Draft_6455.processFrameBinary(Draft_6455.java:862)
> 	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:821)
> 	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:379)
> 	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:216)
> 	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:506)
> 	at java.lang.Thread.run(Thread.java:748)
> java.lang.Exception
> 	at io.colyseus.Client$createMatchMakeRequest$2$1.invoke(Client.kt:316)
> 	at io.colyseus.Client$createMatchMakeRequest$2$1.invoke(Client.kt:19)
> 	at io.colyseus.Room.parseMessage(Room.kt:148)
> 	at io.colyseus.Room.access$parseMessage(Room.kt:20)
> 	at io.colyseus.Room$connect$3.invoke(Room.kt:75)
> 	at io.colyseus.Room$connect$3.invoke(Room.kt:20)
> 	at io.colyseus.Connection.onMessage(Connection.kt:66)
> 	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:598)
> 	at org.java_websocket.drafts.Draft_6455.processFrameBinary(Draft_6455.java:862)
> 	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:821)
> 	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:379)
> 	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:216)
> 	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:506)
> 	at java.lang.Thread.run(Thread.java:748)

@Meabo , did you find the solution?

**Comment by reytum** [comment]
@doorbash Same Issue for me. @Meabo @taluks Did you find the solution?

**Comment by taluks** [comment]
@reytum , try not to use the arena class on the server
